
keys = None

shelter_query = "https://gis.fema.gov/arcgis/rest/services/NSS/FEMA_NSS/FeatureServer/5/query?where=1%3D1&outFields=SHELTER_NAME,CITY,STATE,ZIP,ADA_COMPLIANT,PET_ACCOMMODATIONS_CODE,LATITUDE,LONGITUDE,ORG_ORGANIZATION_NAME,ORG_MAIN_PHONE,ORG_HOTLINE_PHONE,SHELTER_OPEN_DATE,SHELTER_CLOSED_DATE&outSR=4326&f=json"
